[package]
name = "do-core1"
version = "0.1.0"
authors = ["Samuel Ortiz <sameo@linux.intel.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
do-core = { path = "do-core" }

[workspace]
members = [
    "do-core"
]
